"""explain_and_export node.

Explanation text is built exclusively from fields on the selected
RouteCandidate and its score breakdown -- no facts are invented, and
language is deliberately hedged ("better aligned with available map
metadata") rather than making a safety claim the underlying data cannot
support.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable
from datetime import UTC
from pathlib import Path
from typing import Any

from bike_routing_agent.exporters.geojson import to_geojson_str
from bike_routing_agent.exporters.gpx import to_gpx_str
from bike_routing_agent.models import RouteCandidate
from bike_routing_agent.scoring.basic import uncertainty_notes
from bike_routing_agent.state import RouteAgentState
from bike_routing_agent.storage.artifacts import ArtifactStore, LocalArtifactStore
from bike_routing_agent.weather.models import RouteWeather

ExportNodeFn = Callable[[RouteAgentState], dict[str, Any]]


def _loop_sentence(is_loop: bool, loop_plan: dict[str, Any] | None) -> str | None:
    if not is_loop:
        return None
    if loop_plan is None:
        return "It is a loop back to the start, following the waypoints you supplied."
    reach_km = loop_plan["reach_m"] / 1_000
    return (
        "It is a loop back to the start; waypoints were synthesized around the origin "
        f"(reaching about {reach_km:.1f} km out) so the route forms a circuit "
        "rather than an out-and-back."
    )


def _weather_sentences(weather: RouteWeather) -> list[str]:
    """Forecast facts for the explanation; hedged as a forecast, no safety claims."""
    s = weather.summary
    when = weather.departure.astimezone(UTC).strftime("%d %b %H:%M UTC")
    parts: list[str] = []
    if s.temperature_min_c is not None and s.temperature_max_c is not None:
        low, high = round(s.temperature_min_c), round(s.temperature_max_c)
        parts.append(f"{low} °C" if low == high else f"{low} to {high} °C")
    if s.precipitation_probability_max is not None:
        parts.append(f"up to {s.precipitation_probability_max:.0f}% chance of precipitation")
    if s.wind_speed_max_kmh is not None:
        wind = f"wind up to {s.wind_speed_max_kmh:.0f} km/h"
        if s.wind_gust_max_kmh is not None:
            wind += f" (gusts {s.wind_gust_max_kmh:.0f})"
        parts.append(wind)
    if s.headwind_mean_kmh is not None and abs(s.headwind_mean_kmh) >= 5:
        direction = "headwind" if s.headwind_mean_kmh > 0 else "tailwind"
        parts.append(f"about {abs(s.headwind_mean_kmh):.0f} km/h of {direction} on average")
    if not parts:
        return []
    # Every provider whose data is in the forecast, so a merged one is not credited to one only.
    source = " + ".join(weather.sources) if weather.sources else weather.provider
    sentences = [f"Forecast for a {when} departure ({source}): " + ", ".join(parts) + "."]
    if weather.advisories:
        sentences.append("Forecast notes: " + " ".join(weather.advisories))
    return sentences


def _build_explanation(
    candidate: RouteCandidate, *, is_loop: bool = False, loop_plan: dict[str, Any] | None = None
) -> str:
    distance_km = candidate.metrics.distance_m / 1_000
    sentences = [
        f"This {distance_km:.1f} km route was generated by {candidate.provider} "
        f"using the {candidate.provider_profile} profile."
    ]

    loop_sentence = _loop_sentence(is_loop, loop_plan)
    if loop_sentence:
        sentences.append(loop_sentence)

    if candidate.metrics.ascent_m is not None:
        sentences.append(f"It has about {candidate.metrics.ascent_m:.0f} m of ascent.")

    breakdown = candidate.score_breakdown
    if breakdown:
        parts = [f"{name.replace('_', ' ')} {value:.2f}" for name, value in breakdown.items()]
        sentences.append(
            "It was selected as the best-fitting candidate available, "
            "better aligned with the requested constraints and map metadata than the alternatives "
            f"({', '.join(parts)})."
        )

    if candidate.weather is not None:
        sentences.extend(_weather_sentences(candidate.weather))

    if candidate.warnings:
        sentences.append("Provider warnings: " + "; ".join(candidate.warnings) + ".")

    notes = uncertainty_notes(candidate)
    if notes:
        sentences.append("Note: " + "; ".join(notes) + ".")

    sentences.append(
        "This reflects what is better aligned with available map metadata, "
        "not a guarantee of safety."
    )
    return " ".join(sentences)


def build_export_node(
    *, export_dir: Path | None = None, artifact_store: ArtifactStore | None = None
) -> ExportNodeFn:
    """Export node writing GeoJSON/GPX through an :class:`ArtifactStore`.

    ``export_dir`` is the local-disk shorthand (a ``LocalArtifactStore``);
    pass ``artifact_store`` for any other backend (issue #7). Exactly one of
    the two must be given.
    """
    if (export_dir is None) == (artifact_store is None):
        raise ValueError("pass exactly one of export_dir or artifact_store")
    store: ArtifactStore
    if artifact_store is not None:
        store = artifact_store
    else:
        assert export_dir is not None
        store = LocalArtifactStore(export_dir)

    def explain_and_export(state: RouteAgentState) -> dict[str, Any]:
        selected = state.get("selected_candidate")
        if selected is None:
            return {
                "status": "no_route",
                "errors": [{"code": "no_candidates", "message": "no candidate selected"}],
            }

        candidate = RouteCandidate.model_validate(selected)
        explanation = _build_explanation(
            candidate,
            is_loop=bool(state.get("constraints", {}).get("return_to_origin")),
            loop_plan=state.get("loop_plan"),
        )

        route_id = uuid.uuid4().hex
        geojson_name = f"{route_id}.geojson"
        gpx_name = f"{route_id}.gpx"
        store.put(geojson_name, to_geojson_str(candidate))
        store.put(gpx_name, to_gpx_str(candidate, name=route_id))

        return {
            "status": "ready",
            "route_id": route_id,
            "explanation": explanation,
            "artifacts": {
                "geojson_file": geojson_name,
                "gpx_file": gpx_name,
            },
        }

    return explain_and_export
