"""explain_and_export node.

Explanation text is built exclusively from fields on the selected
RouteCandidate and its score breakdown -- no facts are invented, and
language is deliberately hedged ("better aligned with available map
metadata") rather than making a safety claim the underlying data cannot
support.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable
from pathlib import Path
from typing import Any

from bike_routing_agent.exporters.geojson import to_geojson_str
from bike_routing_agent.exporters.gpx import to_gpx_str
from bike_routing_agent.models import RouteCandidate
from bike_routing_agent.scoring.basic import uncertainty_notes
from bike_routing_agent.state import RouteAgentState

ExportNodeFn = Callable[[RouteAgentState], dict[str, Any]]


def _build_explanation(candidate: RouteCandidate) -> str:
    distance_km = candidate.metrics.distance_m / 1_000
    sentences = [f"This {distance_km:.1f} km route was generated by {candidate.provider} "
                 f"using the {candidate.provider_profile} profile."]

    if candidate.metrics.ascent_m is not None:
        sentences.append(f"It has about {candidate.metrics.ascent_m:.0f} m of ascent.")

    breakdown = candidate.score_breakdown
    if breakdown:
        parts = [f"{name.replace('_', ' ')} {value:.2f}" for name, value in breakdown.items()]
        sentences.append(
            "It was selected as the best-fitting candidate available, "
            "better aligned with the requested constraints and map metadata than the alternatives "
            f"({', '.join(parts)})."
        )

    if candidate.warnings:
        sentences.append("Provider warnings: " + "; ".join(candidate.warnings) + ".")

    notes = uncertainty_notes(candidate)
    if notes:
        sentences.append("Note: " + "; ".join(notes) + ".")

    sentences.append(
        "This reflects what is better aligned with available map metadata, "
        "not a guarantee of safety."
    )
    return " ".join(sentences)


def build_export_node(*, export_dir: Path) -> ExportNodeFn:
    export_dir.mkdir(parents=True, exist_ok=True)

    def explain_and_export(state: RouteAgentState) -> dict[str, Any]:
        selected = state.get("selected_candidate")
        if selected is None:
            return {
                "status": "no_route",
                "errors": [{"code": "no_candidates", "message": "no candidate selected"}],
            }

        candidate = RouteCandidate.model_validate(selected)
        explanation = _build_explanation(candidate)

        route_id = uuid.uuid4().hex
        geojson_path = export_dir / f"{route_id}.geojson"
        gpx_path = export_dir / f"{route_id}.gpx"
        geojson_path.write_text(to_geojson_str(candidate))
        gpx_path.write_text(to_gpx_str(candidate, name=route_id))

        return {
            "status": "ready",
            "explanation": explanation,
            "artifacts": {
                "geojson_file": geojson_path.name,
                "gpx_file": gpx_path.name,
            },
        }

    return explain_and_export
