"""What the chat says about a plan: short, factual sentences built from the plan's own data.

Nothing here is generated by a model and nothing is claimed beyond the numbers and the
pros/cons the scoring already produced (docs/scoring-and-exports.md): no safety statements.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from typing import Any

STYLE_NAMES = {
    "custom_gravel-v2": "gravel",
    "custom_gravel-v1": "gravel",
    "custom_touring-v1": "touring",
    "custom_commuter-v1": "commuter",
    "mtb": "mountain bike",
    "fastbike": "fast road",
    "trekking": "trekking",
    "cycling-regular": "regular",
    "cycling-road": "road",
    "cycling-mountain": "mountain",
    "cycling-electric": "electric",
    "bicycle": "standard",
}


def km(meters: float | None) -> str:
    return "?" if meters is None else f"{meters / 1000:.1f} km"


def hours(seconds: float | None) -> str:
    if seconds is None:
        return "?"
    total = round(seconds / 60)
    h, m = divmod(total, 60)
    return f"{h} h {m:02d} min" if h else f"{m} min"


def style(candidate: dict[str, Any]) -> str:
    profile = str(candidate.get("provider_profile") or "")
    return f"{STYLE_NAMES.get(profile, profile)} ({candidate.get('provider')})"


def facts(candidate: dict[str, Any]) -> str:
    m = candidate.get("metrics") or {}
    ascent = m.get("ascent_m")
    parts = [km(m.get("distance_m")), hours(m.get("duration_s"))]
    if ascent is not None:
        parts.append(f"{round(ascent)} m up")
    return ", ".join(parts)


def weather_line(candidate: dict[str, Any]) -> str | None:
    summary = ((candidate.get("weather") or {}).get("summary")) or {}
    if not summary:
        return None
    parts: list[str] = []
    low, high = summary.get("temperature_min_c"), summary.get("temperature_max_c")
    if low is not None and high is not None:
        same = round(low) == round(high)
        parts.append(f"{low:.0f} °C" if same else f"{low:.0f} to {high:.0f} °C")
    if summary.get("wind_speed_mean_kmh") is not None:
        parts.append(f"wind about {summary['wind_speed_mean_kmh']:.0f} km/h")
    head = summary.get("headwind_mean_kmh")
    if head is not None:
        parts.append(f"{abs(head):.0f} km/h {'headwind' if head >= 0 else 'tailwind'} on average")
    prob = summary.get("precipitation_probability_max")
    if prob is not None:
        parts.append(f"rain chance up to {prob:.0f} %")
    stretch = summary.get("wet_stretch")
    if stretch and stretch.get("from_km") is not None and stretch.get("to_km") is not None:
        parts.append(f"wet around km {stretch['from_km']:.0f}-{stretch['to_km']:.0f}")
    if summary.get("after_dark"):
        parts.append("part of the ride is after dark")
    return ", ".join(parts) if parts else None


def place_text(value: Any) -> str:
    if isinstance(value, dict) and value.get("lat") is not None:
        return f"{value['lat']:.4f}, {value['lon']:.4f}"
    return str(value)


def reading(
    request: dict[str, Any],
    *,
    ignored: Sequence[str] = (),
    assumed: Sequence[str] = (),
) -> str:
    """How the request was understood, in a sentence -- so a misreading is visible at once."""
    c = request.get("constraints") or {}
    origin = place_text(request.get("origin"))
    if c.get("return_to_origin"):
        head = f"Planning a {c.get('target_distance_km'):g} km loop from {origin}"
    elif request.get("via") and place_text(request.get("destination")) == origin:
        head = f"Planning a round trip from {origin} to " + ", ".join(
            place_text(v) for v in request["via"]
        )
    else:
        head = f"Planning {origin} to {place_text(request.get('destination'))}"
    if request.get("via") and "round trip" not in head:
        head += " via " + ", ".join(place_text(v) for v in request["via"])
    details: list[str] = []
    if c.get("bike_type"):
        details.append(f"{STYLE_NAMES.get(c['bike_type'], c['bike_type'])} bike")
    if c.get("max_distance_km"):
        details.append(f"at most {c['max_distance_km']:g} km")
    if c.get("max_ascent_m") is not None:
        details.append(f"at most {c['max_ascent_m']:g} m of climbing")
    if c.get("avoid_ferries") is True:
        details.append("no ferries")
    elif c.get("avoid_ferries") is False:
        details.append("ferries allowed")
    if c.get("avoid_high_traffic_roads") is True:
        details.append("quiet roads")
    elif c.get("avoid_high_traffic_roads") is False:
        details.append("busy roads allowed")
    if c.get("prefer_surfaces"):
        details.append("prefer " + "/".join(c["prefer_surfaces"]))
    if c.get("avoid_surfaces"):
        details.append("avoid " + "/".join(c["avoid_surfaces"]))
    if c.get("return_to_origin") and c.get("loop_direction") == "counterclockwise":
        details.append("counter-clockwise")
    stops = (request.get("poi_stops") or {}).get("count")
    if stops:
        details.append(f"past {stops} well-known sight{'s' if stops != 1 else ''}")
    if request.get("routing_engines"):
        details.append("engine " + ", ".join(request["routing_engines"]))
    if request.get("departure_time"):
        details.append("leaving " + _when(str(request["departure_time"])))
    text = head + (f" ({', '.join(details)})" if details else "") + "."
    if assumed:
        text += " Assumed: " + "; ".join(assumed) + "."
    if ignored:
        text += " Not applied: " + "; ".join(ignored) + "."
    return text + " "


def _when(iso: str) -> str:
    from datetime import datetime

    try:
        return datetime.fromisoformat(iso).strftime("%a %d %b, %H:%M")
    except ValueError:
        return iso


def describe_plan(plan: dict[str, Any]) -> str:
    """The reply for a finished plan."""
    route = plan.get("route") or {}
    lines = [f"Here is your route: {facts(route)}, {style(route)} profile."]
    stops = plan.get("poi_stops") or []
    if stops:
        names = ", ".join(str(s.get("name") or s.get("category")) for s in stops)
        lines.append(f"It passes {names}.")
    elif plan.get("poi_stops_status") in ("none_found", "unavailable", "dropped", "unsupported"):
        reasons = {
            "none_found": "I found no well-known sights along this trip",
            "unavailable": "the sight lookup is not available right now",
            "dropped": "the routing engines could not reach the sights by bike",
            "unsupported": "sight stops do not work for loops",
        }
        lines.append(f"No sight stops: {reasons[plan['poi_stops_status']]}.")
    candidates = plan.get("candidates") or []
    if len(candidates) > 1:
        lines.append(
            f"There are {len(candidates)} alternatives; ask me to compare them or pick one."
        )
    weather = weather_line(route)
    if weather:
        lines.append(f"Weather: {weather}.")
    for error in plan.get("errors") or []:
        if error.get("code") == "routing_area_not_covered":
            lines.append(
                "Note: BRouter has no map data for part of this trip, so this comes from another "
                "engine."
            )
    return " ".join(lines)


def limit_notes(request: dict[str, Any], plan: dict[str, Any]) -> str:
    """Where the route is outside what was asked for -- said, not hidden.

    The limits are goals the engines are steered towards, not guarantees: a route that climbs more
    than "max 300 m" or is longer than "at most 70 km" is reported as such.
    """
    c = request.get("constraints") or {}
    m = (plan.get("route") or {}).get("metrics") or {}
    notes: list[str] = []
    ascent, limit = m.get("ascent_m"), c.get("max_ascent_m")
    if ascent is not None and limit is not None and ascent > limit + 1:
        notes.append(f"it still climbs {round(ascent)} m, more than the {limit:g} m asked for")
    distance, cap = m.get("distance_m"), c.get("max_distance_km")
    if distance is not None and cap is not None and distance / 1000 > cap + 0.1:
        notes.append(f"it is {distance / 1000:.1f} km, longer than the {cap:g} km asked for")
    target = c.get("target_distance_km")
    if distance is not None and target and c.get("return_to_origin"):
        if abs(distance / 1000 - target) / target > 0.2:
            notes.append(f"the loop is {distance / 1000:.1f} km, not the {target:g} km asked for")
    if not notes:
        return ""
    return " Note: " + "; ".join(notes) + " -- the engines found nothing closer."


def describe_alternatives(plan: dict[str, Any]) -> str:
    candidates = plan.get("candidates") or []
    if not candidates:
        return "There are no alternatives for this route."
    lines = ["Alternatives (best first):"]
    for c in candidates:
        lines.append(f"{c.get('rank')}. {style(c)}: {facts(c)}")
        lines.extend(f"   + {p}" for p in c.get("pros") or [])
        lines.extend(f"   - {p}" for p in c.get("cons") or [])
    return "\n".join(lines)


def describe_candidate(candidate: dict[str, Any]) -> str:
    lines = [f"Showing the {style(candidate)} route: {facts(candidate)}."]
    lines.extend(f"+ {p}" for p in candidate.get("pros") or [])
    lines.extend(f"- {p}" for p in candidate.get("cons") or [])
    return "\n".join(lines)


def explain(question: str, plan: dict[str, Any]) -> str:
    """Answer a question about the last route from what the plan holds."""
    route = plan.get("route") or {}
    metrics = route.get("metrics") or {}
    q = question.lower()
    parts: list[str] = []
    asked = False
    if re.search(r"weather|rain|wind|temperature|cold|warm|hot|sunset|sunrise|dark|daylight", q):
        asked = True
        line = weather_line(route)
        parts.append(
            f"Weather along the route: {line}."
            if line
            else "I have no forecast for this route (off, unavailable, or too far ahead)."
        )
    if re.search(r"how (?:far|long)|distance|duration|how fast|km", q):
        asked = True
        distance, duration = km(metrics.get("distance_m")), hours(metrics.get("duration_s"))
        parts.append(f"It is {distance} and takes about {duration}.")
    if re.search(r"steep|hilly|climb|ascent|elevation|flat", q):
        asked = True
        up, down = metrics.get("ascent_m"), metrics.get("descent_m")
        parts.append(
            f"It climbs {round(up)} m"
            + (f" and descends {round(down)} m." if down is not None else ".")
            if up is not None
            else "The engine did not report the climb for this route."
        )
    if re.search(r"surface|paved|unpaved|gravel|asphalt", q):
        asked = True
        coverage = metrics.get("engine_surface_shares") or metrics.get("surface_coverage") or {}
        if coverage:
            shown = ", ".join(
                f"{round(100 * v)} % {k}"
                for k, v in sorted(coverage.items(), key=lambda kv: -kv[1])[:4]
            )
            parts.append(f"Surfaces (as mapped): {shown}.")
        else:
            parts.append("I have no surface data for this route.")
    if re.search(r"why|explain|pros|cons|better|best", q) or not asked:
        if plan.get("explanation") and re.search(r"why|explain", q):
            parts.append(str(plan["explanation"]))
        pros, cons = route.get("pros") or [], route.get("cons") or []
        if pros or cons:
            parts.append(
                "Compared with the alternatives: "
                + "; ".join([*(f"+ {p}" for p in pros), *(f"- {c}" for c in cons)])
                + "."
            )
        elif not asked:
            parts.append(f"It is {facts(route)}, {style(route)} profile.")
    return " ".join(parts) if parts else f"It is {facts(route)}."


def suggestions_after_plan(plan: dict[str, Any], *, sights: bool, export: bool = True) -> list[str]:
    options = ["Alternatives"] if len(plan.get("candidates") or []) > 1 else []
    options += ["Make it shorter", "What's the weather?"]
    if sights:
        options.append("What sights are along the way?")
    if export and plan.get("artifacts"):
        options.append("Send me the GPX")
    options.append("New route")
    return options[:6]
