"""What the chat says about a plan: short, factual sentences built from the plan's own data.

Nothing here is generated by a model and nothing is claimed beyond the numbers and the
pros/cons the scoring already produced (docs/scoring-and-exports.md): no safety statements.
"""

from __future__ import annotations

import re
from typing import Any

STYLE_NAMES = {
    "custom_gravel-v2": "gravel",
    "custom_gravel-v1": "gravel",
    "custom_touring-v1": "touring",
    "custom_commuter-v1": "commuter",
    "mtb": "mountain bike",
    "fastbike": "fast road",
    "trekking": "trekking",
    "cycling-regular": "regular",
    "cycling-road": "road",
    "cycling-mountain": "mountain",
    "cycling-electric": "electric",
    "bicycle": "standard",
}


def km(meters: float | None) -> str:
    return "?" if meters is None else f"{meters / 1000:.1f} km"


def hours(seconds: float | None) -> str:
    if seconds is None:
        return "?"
    total = round(seconds / 60)
    h, m = divmod(total, 60)
    return f"{h} h {m:02d} min" if h else f"{m} min"


def style(candidate: dict[str, Any]) -> str:
    profile = str(candidate.get("provider_profile") or "")
    return f"{STYLE_NAMES.get(profile, profile)} ({candidate.get('provider')})"


def facts(candidate: dict[str, Any]) -> str:
    m = candidate.get("metrics") or {}
    ascent = m.get("ascent_m")
    parts = [km(m.get("distance_m")), hours(m.get("duration_s"))]
    if ascent is not None:
        parts.append(f"{round(ascent)} m up")
    return ", ".join(parts)


def weather_line(candidate: dict[str, Any]) -> str | None:
    summary = ((candidate.get("weather") or {}).get("summary")) or {}
    if not summary:
        return None
    parts: list[str] = []
    low, high = summary.get("temperature_min_c"), summary.get("temperature_max_c")
    if low is not None and high is not None:
        parts.append(f"{low:.0f} to {high:.0f} °C")
    if summary.get("wind_speed_mean_kmh") is not None:
        parts.append(f"wind about {summary['wind_speed_mean_kmh']:.0f} km/h")
    head = summary.get("headwind_mean_kmh")
    if head is not None:
        parts.append(f"{abs(head):.0f} km/h {'headwind' if head >= 0 else 'tailwind'} on average")
    prob = summary.get("precipitation_probability_max")
    if prob is not None:
        parts.append(f"rain chance up to {prob:.0f} %")
    stretch = summary.get("wet_stretch")
    if stretch and stretch.get("from_km") is not None and stretch.get("to_km") is not None:
        parts.append(f"wet around km {stretch['from_km']:.0f}-{stretch['to_km']:.0f}")
    if summary.get("after_dark"):
        parts.append("part of the ride is after dark")
    return ", ".join(parts) if parts else None


def describe_plan(plan: dict[str, Any]) -> str:
    """The reply for a finished plan."""
    route = plan.get("route") or {}
    lines = [f"Here is your route: {facts(route)}, {style(route)} profile."]
    stops = plan.get("poi_stops") or []
    if stops:
        names = ", ".join(str(s.get("name") or s.get("category")) for s in stops)
        lines.append(f"It passes {names}.")
    elif plan.get("poi_stops_status") in ("none_found", "unavailable", "dropped", "unsupported"):
        reasons = {
            "none_found": "I found no well-known sights along this trip",
            "unavailable": "the sight lookup is not available right now",
            "dropped": "the routing engines could not reach the sights by bike",
            "unsupported": "sight stops do not work for loops",
        }
        lines.append(f"No sight stops: {reasons[plan['poi_stops_status']]}.")
    candidates = plan.get("candidates") or []
    if len(candidates) > 1:
        lines.append(
            f"There are {len(candidates)} alternatives; ask me to compare them or pick one."
        )
    weather = weather_line(route)
    if weather:
        lines.append(f"Weather: {weather}.")
    for error in plan.get("errors") or []:
        if error.get("code") == "routing_area_not_covered":
            lines.append(
                "Note: BRouter has no map data for part of this trip, so this comes from another "
                "engine."
            )
    return " ".join(lines)


def describe_alternatives(plan: dict[str, Any]) -> str:
    candidates = plan.get("candidates") or []
    if not candidates:
        return "There are no alternatives for this route."
    lines = ["Alternatives (best first):"]
    for c in candidates:
        lines.append(f"{c.get('rank')}. {style(c)}: {facts(c)}")
        lines.extend(f"   + {p}" for p in c.get("pros") or [])
        lines.extend(f"   - {p}" for p in c.get("cons") or [])
    return "\n".join(lines)


def describe_candidate(candidate: dict[str, Any]) -> str:
    lines = [f"Showing the {style(candidate)} route: {facts(candidate)}."]
    lines.extend(f"+ {p}" for p in candidate.get("pros") or [])
    lines.extend(f"- {p}" for p in candidate.get("cons") or [])
    return "\n".join(lines)


def explain(question: str, plan: dict[str, Any]) -> str:
    """Answer a question about the last route from what the plan holds."""
    route = plan.get("route") or {}
    metrics = route.get("metrics") or {}
    q = question.lower()
    parts: list[str] = []
    asked = False
    if re.search(r"weather|rain|wind|temperature|cold|warm|hot|sunset|sunrise|dark|daylight", q):
        asked = True
        line = weather_line(route)
        parts.append(
            f"Weather along the route: {line}."
            if line
            else "I have no forecast for this route (off, unavailable, or too far ahead)."
        )
    if re.search(r"how (?:far|long)|distance|duration|how fast|km", q):
        asked = True
        distance, duration = km(metrics.get("distance_m")), hours(metrics.get("duration_s"))
        parts.append(f"It is {distance} and takes about {duration}.")
    if re.search(r"steep|hilly|climb|ascent|elevation|flat", q):
        asked = True
        up, down = metrics.get("ascent_m"), metrics.get("descent_m")
        parts.append(
            f"It climbs {round(up)} m"
            + (f" and descends {round(down)} m." if down is not None else ".")
            if up is not None
            else "The engine did not report the climb for this route."
        )
    if re.search(r"surface|paved|unpaved|gravel|asphalt", q):
        asked = True
        coverage = metrics.get("engine_surface_shares") or metrics.get("surface_coverage") or {}
        if coverage:
            shown = ", ".join(
                f"{round(100 * v)} % {k}"
                for k, v in sorted(coverage.items(), key=lambda kv: -kv[1])[:4]
            )
            parts.append(f"Surfaces (as mapped): {shown}.")
        else:
            parts.append("I have no surface data for this route.")
    if re.search(r"why|explain|pros|cons|better|best", q) or not asked:
        if plan.get("explanation") and re.search(r"why|explain", q):
            parts.append(str(plan["explanation"]))
        pros, cons = route.get("pros") or [], route.get("cons") or []
        if pros or cons:
            parts.append(
                "Compared with the alternatives: "
                + "; ".join([*(f"+ {p}" for p in pros), *(f"- {c}" for c in cons)])
                + "."
            )
        elif not asked:
            parts.append(f"It is {facts(route)}, {style(route)} profile.")
    return " ".join(parts) if parts else f"It is {facts(route)}."


def suggestions_after_plan(plan: dict[str, Any], *, sights: bool, export: bool = True) -> list[str]:
    options = ["Alternatives"] if len(plan.get("candidates") or []) > 1 else []
    options += ["Make it shorter", "What's the weather?"]
    if sights:
        options.append("What sights are along the way?")
    if export and plan.get("artifacts"):
        options.append("Send me the GPX")
    options.append("New route")
    return options[:6]
